# Generated by Django 5.2 on 2025-04-06 10:20

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GaliDpeAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_analyse', models.IntegerField(db_comment="Version du moteur d'analyse", db_index=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('classification', models.CharField(blank=True, db_comment='Classification manuelle', db_index=True, max_length=100, null=True)),
                ('a_ignorer', models.BooleanField(db_comment='Ignorer ce DPE', db_index=True, default=False)),
                ('precision_min', models.FloatField(blank=True, null=True)),
                ('precision_avg', models.FloatField(blank=True, null=True)),
                ('precision_max', models.FloatField(blank=True, null=True)),
                ('incoherence_min', models.FloatField(blank=True, null=True)),
                ('incoherence_avg', models.FloatField(blank=True, null=True)),
                ('incoherence_max', models.FloatField(blank=True, null=True)),
                ('fiabilite_admin_min', models.FloatField(blank=True, null=True)),
                ('fiabilite_admin_avg', models.FloatField(blank=True, null=True)),
                ('fiabilite_admin_max', models.FloatField(blank=True, null=True)),
                ('severite_max', models.IntegerField(blank=True, db_index=True, null=True)),
                ('a_corriger', models.BooleanField(blank=True, default=False, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'galidpe_analyse',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GaliDpeDiagnostiqueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_logiciel_id', models.CharField(blank=True, max_length=100, null=True)),
                ('version_logiciel', models.CharField(blank=True, max_length=100, null=True)),
                ('version_moteur_calcul', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_diagnostiqueur', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom_diagnostiqueur', models.CharField(blank=True, max_length=100, null=True)),
                ('mail_diagnostiqueur', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone_diagnostiqueur', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse_diagnostiqueur', models.CharField(blank=True, max_length=100, null=True)),
                ('entreprise_diagnostiqueur', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_certification_diagnostiqueur', models.CharField(blank=True, max_length=100, null=True)),
                ('organisme_certificateur', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'galidpe_diagnostiqueur',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GaliDpeAnomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('titre', models.CharField(blank=True, max_length=100, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('incoherence', models.FloatField(blank=True, null=True)),
                ('fiabilite_admin', models.FloatField(blank=True, null=True)),
                ('severite', models.IntegerField()),
                ('analyse_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galidpe.galidpeanalyse')),
            ],
            options={
                'db_table': 'dgalidpe_anomalie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GaliDpeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpe_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ademe', models.CharField(blank=True, db_index=True, max_length=13, null=True, unique=True)),
                ('date_etablissement_dpe', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ug', models.CharField(blank=True, db_comment='Identifiant de gestion', db_index=True, max_length=100, null=True)),
                ('surface_habitable_logement', models.FloatField(blank=True, null=True)),
                ('conso_val', models.FloatField(blank=True, null=True)),
                ('ges_val', models.FloatField(blank=True, null=True)),
                ('conso_lettre', models.CharField(blank=True, max_length=1, null=True)),
                ('ges_lettre', models.CharField(blank=True, max_length=1, null=True)),
                ('classe', models.CharField(blank=True, max_length=1, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('cp', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=255, null=True)),
                ('depot_source', models.CharField(blank=True, db_comment="Chemin d'origine du DPE", max_length=1000, null=True)),
                ('commentaire_travaux', models.CharField(blank=True, max_length=1000, null=True)),
                ('tsv', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('diagnostiqueur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='galidpe.galidpediagnostiqueur')),
            ],
            options={
                'db_table': 'galidpe_info',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='galidpeanalyse',
            name='dpe_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galidpe.galidpeinfo'),
        ),
        migrations.CreateModel(
            name='GaliDpeJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpe_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('ademe', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('json', models.JSONField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('dpe_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galidpe.galidpeinfo')),
            ],
            options={
                'db_table': 'galidpe_json',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='galidpeinfo',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tsv'], name='idx_galidpeinfo_tsv'),
        ),
    ]
