# Generated by Django 5.2 on 2025-04-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galidpe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galidpeanalyse',
            name='ademe',
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True),
        ),
    ]
