# Generated by Django 5.2 on 2025-04-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galidpe', '0002_galidpeanalyse_ademe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galidpeanalyse',
            name='dpe_info',
        ),
        migrations.AlterField(
            model_name='galidpeanalyse',
            name='ademe',
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True, unique=True),
        ),
    ]
