# Generated by Django 5.2 on 2025-04-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galidpe', '0003_remove_galidpeanalyse_dpe_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galidpeinfo',
            name='dpe_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
