# Generated by Django 5.2 on 2025-04-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galidpe', '0004_alter_galidpeinfo_dpe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galidpeanalyse',
            name='commentaire',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
