# Generated by Django 5.2 on 2025-04-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galidpe', '0005_alter_galidpeanalyse_commentaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galidpeanalyse',
            old_name='commentaire',
            new_name='anomalies',
        ),
        migrations.AddField(
            model_name='galidpeanalyse',
            name='commentaires',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='GaliDpeAnomalie',
        ),
    ]
