# Generated by Django 5.2 on 2025-04-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galidpe', '0006_rename_commentaire_galidpeanalyse_anomalies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galidpeanalyse',
            name='connaissances',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galidpeanalyse',
            name='erreurs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
