# Generated by Django 5.2 on 2025-04-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dpebaievitreemasque',
            options={'default_permissions': (), 'managed': False},
        ),
    ]
