# Generated by Django 5.2 on 2025-04-03 22:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpeInfos',
            fields=[
                ('dpe_id', models.OneToOneField(db_column='dpe_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dpe.dpe')),
                ('ademe', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('ug', models.CharField(blank=True, db_comment='Identifiant de gestion', db_index=True, max_length=100, null=True)),
                ('surface_habitable_logement', models.FloatField(blank=True, db_index=True, null=True)),
                ('conso_val', models.FloatField(blank=True, db_index=True, null=True)),
                ('ges_val', models.FloatField(blank=True, db_index=True, null=True)),
                ('conso_lettre', models.CharField(blank=True, db_index=True, max_length=1, null=True)),
                ('ges_lettre', models.CharField(blank=True, db_index=True, max_length=1, null=True)),
                ('classe', models.CharField(blank=True, db_index=True, max_length=1, null=True)),
                ('adresse', models.CharField(blank=True, db_index=True, max_length=1000, null=True)),
                ('cp', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('ville', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('depot_source', models.CharField(blank=True, max_length=1000, null=True)),
                ('usr_logiciel_id', models.CharField(blank=True, max_length=100, null=True)),
                ('version_logiciel', models.CharField(blank=True, max_length=100, null=True)),
                ('version_moteur_calcul', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_diagnostiqueur', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom_diagnostiqueur', models.CharField(blank=True, max_length=100, null=True)),
                ('mail_diagnostiqueur', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone_diagnostiqueur', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse_diagnostiqueur', models.CharField(blank=True, max_length=100, null=True)),
                ('entreprise_diagnostiqueur', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_certification_diagnostiqueur', models.CharField(blank=True, max_length=100, null=True)),
                ('organisme_certificateur', models.CharField(blank=True, max_length=100, null=True)),
                ('invar_logement', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_fiscal_local', models.CharField(blank=True, max_length=100, null=True)),
                ('rpls_org_id', models.CharField(blank=True, max_length=100, null=True)),
                ('enum_consentement_formulaire_id', models.CharField(blank=True, max_length=10, null=True)),
                ('nom_formulaire', models.CharField(blank=True, max_length=100, null=True)),
                ('personne_morale', models.CharField(blank=True, max_length=100, null=True)),
                ('siren_formulaire', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('mail', models.CharField(blank=True, max_length=100, null=True)),
                ('label_adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('label_adresse_avec_complement', models.CharField(blank=True, max_length=100, null=True)),
                ('commentaire_travaux', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'dpe_infos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DpeJson',
            fields=[
                ('dpe_id', models.OneToOneField(db_column='dpe_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dpe.dpe')),
                ('ademe', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, db_index=True, default='original', max_length=100, null=True)),
                ('json_content', models.TextField(blank=True, db_comment='Contenu json du DPE', null=True)),
            ],
            options={
                'db_table': 'dpe_json',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='dpe',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dpepacktravaux',
            name='dpe_id',
            field=models.ForeignKey(blank=True, db_column='dpe_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dpe.dpe'),
        ),
        migrations.AlterField(
            model_name='compteurimportdpecertificat',
            name='alerte_envoyee',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='compteurimportdpecertificat',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='compteurimportdpecertificat',
            name='id_utilisateur_diagnostiqueur',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compteurimportdpecertificat',
            name='id_utilisateur_organisme_certificateur',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compteurimportdpecertificat',
            name='nombre_dpe_importes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='compteurimportdpecertificat',
            name='numero_certificat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandetelechargementattestation',
            name='fichier_supprime',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='demandetelechargementattestation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='demandetelechargementattestation',
            name='id_organisme',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandetelechargementattestation',
            name='statut_telechargement',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dpe',
            name='anonymise',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dpe',
            name='date_derniere_modification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dpe',
            name='date_reception_dpe',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dpe',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpe',
            name='is_dpe_2012',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dpe',
            name='suppression_en_cours',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dpe',
            name='traite_petite_surface',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dpe2012enummodeledpe',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dpe2012enummodeledpe',
            name='est_efface',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dpe2012enummodeledpe',
            name='modele',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dpeadministratif',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeadministratif',
            name='date_fin_validite_dpe',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeadministratif',
            name='enum_version_id',
            field=models.CharField(blank=True, db_comment=' modèle concerné : tous | description : version du DPE. Pour gérer toute future évolution du dispositif et du modèle de données sous jacent (ex. modification des tv reseau de chaleur) ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dpeadministratif',
            name='is_dpe_2012',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeapportetbesoin',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpebaieets',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpebaieets',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpebaieets',
            name='nb_baie',
            field=models.FloatField(db_comment=' modèle concerné : logement | description : nombre de baies ', null=True),
        ),
        migrations.AlterField(
            model_name='dpebaievitree',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpebaievitree',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpebaievitreedoublefenetre',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpebaievitreemasque',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpebilanconsommation',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpecaracteristiquegenerale',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpecaracteristiquegenerale',
            name='is_dpe_2012',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeclimatisation',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeclimatisation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpeconfortete',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeconsommation',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeconsommation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpeconsommation',
            name='is_dpe_2012',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dpecout',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpedeperdition',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpedescriptifenr',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpedescriptifenr',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpeefconso',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeemetteurchauffage',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeemetteurchauffage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpeemissionges',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeemissionges',
            name='is_dpe_2012',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumbouclagereseauecs',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumcalculechantillonnage',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumcategoriedescriptifsimplifie',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumcategorieenrdescriptif',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumcategorieerp',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumcategoriefichetechnique',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumcfginstallationch',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumcfginstallationecs',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumcfgisolationlnc',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumclassealtitude',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumclasseetiquette',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumclasseinertie',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumequipementintermittence',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenuminclinaisonpv',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenuminclinaisonvitrage',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumindicateurconfortete',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumliengenerateuremetteur',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumlottravaux',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenummateriauxstructuremur',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenummethodeapplicationdpelog',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenummethodeapplicationdpeter',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenummethodecalculconso',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenummethodesaisiecaracsys',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenummethodesaisiefactcouvsol',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenummethodesaisieperfvitrage',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenummethodesaisiepontthermique',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenummethodesaisieq4paconv',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenummethodesaisieu',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenummethodesaisieu0',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenummethodesaisieuporte',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenummodeledpe',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumnumpacktravaux',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumorientation',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumorientationpv',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumoriginedonnee',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumperiodeconstruction',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumperiodeinstallationecsthermo',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumperiodeinstallationemetteur',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumperiodeinstallationfr',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumperiodeisolation',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumpictogesteentretien',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumpositionetagelogement',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumqualitecomposant',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumsecteur',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumsousmodeledpeter',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumstatutgeocodageban',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtempdistributionch',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypeadjacence',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypebaie',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypechauffage',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypedoublage',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypeemissiondistribution',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypeenergie',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypeenr',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypefermeture',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypegazlame',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypegenerateurch',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypegenerateurecs',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypegenerateurfr',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypeinstallation',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypeinstallationsolaire',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypeisolation',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypejustificatif',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypeliaison',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypemateriauxmenuiserie',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypeplancherbas',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypeplancherhaut',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypeporte',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypepose',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtyperegulation',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypestockageecs',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypeusage',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypeventilation',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypevitrage',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumtypologielogement',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumusagefonctionnelbatiment',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumusagegenerateur',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumversion',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeenumzoneclimatique',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeepconso',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeepconso',
            name='is_dpe_2012',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeets',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeets',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpegenerateurchauffage',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpegenerateurchauffage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpegenerateurchauffage',
            name='is_dpe_2012',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dpegenerateurecs',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpegenerateurecs',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpegenerateurecs',
            name='is_dpe_2012',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dpegeolocalisation',
            name='administratif',
            field=models.OneToOneField(db_column='administratif', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dpe.dpeadministratif'),
        ),
        migrations.AlterField(
            model_name='dpegeolocalisation',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpegeolocalisation',
            name='is_dpe_2012',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeinertie',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeinstallationchauffage',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeinstallationchauffage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpeinstallationchauffage',
            name='is_dpe_2012',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeinstallationecs',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeinstallationecs',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpeinstallationecs',
            name='is_dpe_2012',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dpejustificatif',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpejustificatif',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpelogementvisite',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpelogementvisite',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpemasquelointainnonhomogene',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpemasquelointainnonhomogene',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpemeteo',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpemeteo',
            name='is_dpe_2012',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dpemur',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpemur',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpepacktravaux',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpepacktravaux',
            name='descriptif_travaux_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='dpepacktravaux',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpepanneauxpv',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpepanneauxpv',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpeplancherbas',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeplancherbas',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpeplancherhaut',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeplancherhaut',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpepontthermique',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpepontthermique',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpeporte',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeporte',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpeproductionelecenr',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeproductionelectricite',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpequaliteisolation',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dperepartitionchauffage',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dperepartitionecs',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpesortieparenergie',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpesortieparenergie',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpetadresse',
            name='adresse_brut',
            field=models.CharField(db_comment=" modèle concerné : tous | description : champs texte brute de l'adresse saisi par le diagnostiqueur ", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dpetadresse',
            name='ban_date_appel',
            field=models.DateTimeField(blank=True, db_comment=" modèle concerné : tous | description : date d'appel à la ban ", null=True),
        ),
        migrations.AlterField(
            model_name='dpetadresse',
            name='ban_erreur',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetadresse',
            name='code_postal_brut',
            field=models.CharField(db_comment=" modèle concerné : tous | description : code postal de l'adresse brute saisie par le diagnostiqueur ", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dpetadresse',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetadresse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpetadresse',
            name='is_dpe_2012',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetadresse',
            name='label_brut',
            field=models.CharField(db_comment=" modèle concerné : tous | description : label complet de l'adresse saisie par le diagnostiqueur (adresse + code postal + nom commune) ", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dpetadresse',
            name='migre_en_utc',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetadresse',
            name='nom_commune_brut',
            field=models.CharField(db_comment=' modèle concerné : tous | description : nom de commune brute saisie par le diagnostiqueur ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dpetadresse',
            name='traite_par_batch',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvcoefmasquelointainhomogene',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvcoefmasquelointainnonhomoge',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvcoefmasqueproche',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvcoeforientationpv',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvcoefreductiondeperdition',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvcoeftransparenceets',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvdebitsventilation',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvdeltar',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvfacteurcouverturesolaire',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvgenerateurcombustion',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvintermittence',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvpertesstockage',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvpontthermique',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvq4paconv',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvrendementdistributionch',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvrendementdistributionecs',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvrendementemission',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvrendementgeneration',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvrendementregulation',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvreseauchaleur2020',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvreseauchaleur2021',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvreseauchaleur2022',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvscop',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvseer',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvsw',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvtempfonc100',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvtempfonc30',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvtypegenerateurch',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvtypegenerateurecs',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvue',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvug',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvujn',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvumur',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvumur0',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvupb',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvupb0',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvuph',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvuph0',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvuporte',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvuvue',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpetvuw',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeventilation',
            name='date_derniere_modification',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dpeventilation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seuilpetitesurface',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thematiquecontact',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='DpeAnalyse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ademe', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('version_analyse', models.IntegerField(db_comment="Version du moteur d'analyse", db_index=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('classification', models.CharField(blank=True, db_comment='Classification manuelle', db_index=True, max_length=100, null=True)),
                ('a_ignorer', models.BooleanField(db_comment='Ignorer ce DPE', db_index=True, default=False)),
                ('precision_min', models.FloatField(blank=True, null=True)),
                ('precision_avg', models.FloatField(blank=True, null=True)),
                ('precision_max', models.FloatField(blank=True, null=True)),
                ('incoherence_min', models.FloatField(blank=True, null=True)),
                ('incoherence_avg', models.FloatField(blank=True, null=True)),
                ('incoherence_max', models.FloatField(blank=True, null=True)),
                ('fiabilite_admin_min', models.FloatField(blank=True, null=True)),
                ('fiabilite_admin_avg', models.FloatField(blank=True, null=True)),
                ('fiabilite_admin_max', models.FloatField(blank=True, null=True)),
                ('severite_max', models.IntegerField(blank=True, db_index=True, null=True)),
                ('a_corriger', models.BooleanField(blank=True, default=False, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('dpe_id', models.ForeignKey(blank=True, db_column='dpe_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dpe.dpe')),
            ],
            options={
                'db_table': 'dpe_analyse',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DpeAnomalie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('titre', models.CharField(blank=True, max_length=100, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('incoherence', models.FloatField(blank=True, null=True)),
                ('fiabilite_admin', models.FloatField(blank=True, null=True)),
                ('severite', models.IntegerField()),
                ('analyse_id', models.ForeignKey(blank=True, db_column='analyse_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dpe.dpeanalyse')),
            ],
            options={
                'db_table': 'dpe_anomalie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DpeDescriptifSimplifie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('enum_categorie_descriptif_simplifie_id', models.IntegerField(blank=True, db_comment=' modèle concerné : logement + logement neuf | description : catégorie de système ENR ', null=True)),
                ('dpe_id', models.ForeignKey(blank=True, db_column='dpe_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dpe.dpe')),
            ],
            options={
                'db_table': 'dpe_descriptif_simplifie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DpeFicheTechnique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('enum_categorie_fiche_technique_id', models.IntegerField(blank=True, null=True)),
                ('dpe_id', models.ForeignKey(blank=True, db_column='dpe_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dpe.dpe')),
            ],
            options={
                'db_table': 'dpe_fiche_technique',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DpeGesteEntretien',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('enum_picto_geste_entretien_id', models.IntegerField(blank=True, null=True)),
                ('categorie_geste_entretien', models.CharField(blank=True, max_length=255, null=True)),
                ('dpe_id', models.ForeignKey(blank=True, db_column='dpe_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dpe.dpe')),
            ],
            options={
                'db_table': 'dpe_geste_entretien',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DpeSousFicheTechnique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('valeur', models.CharField(blank=True, max_length=255, null=True)),
                ('detail_origine_donnee', models.CharField(blank=True, max_length=255, null=True)),
                ('enum_origine_donnee_id', models.IntegerField(blank=True, null=True)),
                ('dpe_id', models.ForeignKey(blank=True, db_column='dpe_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dpe.dpe')),
                ('fiche_technique_id', models.ForeignKey(blank=True, db_column='fiche_technique_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dpe.dpefichetechnique')),
            ],
            options={
                'db_table': 'dpe_sous_fiche_technique',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DpeTravaux',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description_travaux', models.TextField(blank=True, null=True)),
                ('performance_recommande', models.CharField(blank=True, max_length=255, null=True)),
                ('avertissement_travaux', models.CharField(blank=True, max_length=255, null=True)),
                ('enum_lot_travaux_id', models.IntegerField(blank=True, null=True)),
                ('dpe_id', models.ForeignKey(blank=True, db_column='dpe_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dpe.dpe')),
                ('pack_travaux_id', models.ForeignKey(blank=True, db_column='pack_travaux_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dpe.dpepacktravaux')),
            ],
            options={
                'db_table': 'dpe_travaux',
                'managed': True,
            },
        ),
    ]
