# Generated by Django 5.2 on 2025-04-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpe', '0002_alter_dpebaievitreemasque_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dpebaievitreemasque',
            options={'managed': False},
        ),
    ]
